CREATE TABLE app_user (
                          id UUID PRIMARY KEY,

                          email VARCHAR(254) NOT NULL UNIQUE,

                          display_name VARCHAR(120) NOT NULL,

                          role VARCHAR(20) NOT NULL,

                          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                          CONSTRAINT ck_app_user_role
                              CHECK (role IN ('MANAGER', 'CLERK'))
);


CREATE TABLE supplier (
                          id UUID PRIMARY KEY,

                          code VARCHAR(20) NOT NULL UNIQUE,

                          name VARCHAR(160) NOT NULL,

                          email VARCHAR(254),

                          phone VARCHAR(40),

                          is_active BOOLEAN NOT NULL DEFAULT TRUE,

                          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                          version INTEGER NOT NULL DEFAULT 1
);


CREATE TABLE product (
                         id UUID PRIMARY KEY,

                         sku VARCHAR(50) NOT NULL UNIQUE,

                         name VARCHAR(160) NOT NULL,

                         description VARCHAR(500),

                         supplier_id UUID,

                         unit VARCHAR(16) NOT NULL DEFAULT 'EACH',

                         quantity_on_hand INTEGER NOT NULL DEFAULT 0,

                         reorder_level INTEGER NOT NULL DEFAULT 0,

                         is_active BOOLEAN NOT NULL DEFAULT TRUE,

                         created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                         updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                         version INTEGER NOT NULL DEFAULT 1,

                         CONSTRAINT fk_product_supplier
                             FOREIGN KEY (supplier_id)
                                 REFERENCES supplier(id)
                                 ON DELETE SET NULL,

                         CONSTRAINT ck_product_quantity
                             CHECK (quantity_on_hand >= 0),

                         CONSTRAINT ck_product_reorder_level
                             CHECK (reorder_level >= 0)
);


CREATE TABLE stock_movement (
                                id UUID PRIMARY KEY,

                                product_id UUID NOT NULL,

                                movement_type VARCHAR(20) NOT NULL,

                                quantity INTEGER NOT NULL,

                                reference VARCHAR(80),

                                note VARCHAR(250),

                                occurred_at TIMESTAMPTZ NOT NULL,

                                recorded_by UUID NOT NULL,

                                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                                CONSTRAINT fk_movement_product
                                    FOREIGN KEY (product_id)
                                        REFERENCES product(id)
                                        ON DELETE RESTRICT,

                                CONSTRAINT fk_movement_recorded_by
                                    FOREIGN KEY (recorded_by)
                                        REFERENCES app_user(id)
                                        ON DELETE RESTRICT,

                                CONSTRAINT ck_movement_type
                                    CHECK (
                                        movement_type IN (
                                                          'RECEIPT',
                                                          'ISSUE',
                                                          'ADJUSTMENT_IN',
                                                          'ADJUSTMENT_OUT'
                                            )
                                        ),

                                CONSTRAINT ck_movement_quantity
                                    CHECK (quantity > 0)
);


CREATE INDEX ix_product_low_stock
    ON product (
                is_active,
                quantity_on_hand,
                reorder_level
        );


CREATE INDEX ix_movement_product_occurred
    ON stock_movement (
                       product_id,
                       occurred_at DESC
        );


CREATE INDEX ix_movement_occurred
    ON stock_movement (
                       occurred_at DESC
        );
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
    )

